//go:build !ignore_autogenerated

// Copyright 2026 SSM Annotation Resolver Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SsmAnnotationResolverInfra) DeepCopyInto(out *SsmAnnotationResolverInfra) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SsmAnnotationResolverInfra.
func (in *SsmAnnotationResolverInfra) DeepCopy() *SsmAnnotationResolverInfra {
	if in == nil {
		return nil
	}
	out := new(SsmAnnotationResolverInfra)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SsmAnnotationResolverInfra) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SsmAnnotationResolverInfraList) DeepCopyInto(out *SsmAnnotationResolverInfraList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SsmAnnotationResolverInfra, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SsmAnnotationResolverInfraList.
func (in *SsmAnnotationResolverInfraList) DeepCopy() *SsmAnnotationResolverInfraList {
	if in == nil {
		return nil
	}
	out := new(SsmAnnotationResolverInfraList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SsmAnnotationResolverInfraList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SsmAnnotationResolverInfraOutputs) DeepCopyInto(out *SsmAnnotationResolverInfraOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SsmAnnotationResolverInfraOutputs.
func (in *SsmAnnotationResolverInfraOutputs) DeepCopy() *SsmAnnotationResolverInfraOutputs {
	if in == nil {
		return nil
	}
	out := new(SsmAnnotationResolverInfraOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SsmAnnotationResolverInfraStatus) DeepCopyInto(out *SsmAnnotationResolverInfraStatus) {
	*out = *in
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = new(SsmAnnotationResolverInfraOutputs)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SsmAnnotationResolverInfraStatus.
func (in *SsmAnnotationResolverInfraStatus) DeepCopy() *SsmAnnotationResolverInfraStatus {
	if in == nil {
		return nil
	}
	out := new(SsmAnnotationResolverInfraStatus)
	in.DeepCopyInto(out)
	return out
}
