{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "ssm-annotation-resolver.fullname" . }}-mutating-webhook
  labels:
    {{- include "ssm-annotation-resolver.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "ssm-annotation-resolver.namespace" . }}/{{ include "ssm-annotation-resolver.fullname" . }}-webhook-certificate
  {{- end }}
webhooks:
  - name: {{ include "ssm-annotation-resolver.fullname" . }}.ssm-annotation-resolver.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded
    {{- with .Values.webhook.namespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.webhook.objectSelector }}
    objectSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    rules:
      - operations:
          {{- range .Values.webhook.rules.operations }}
          - {{ . | quote }}
          {{- end }}
        apiGroups:
          {{- range .Values.webhook.rules.apiGroups }}
          - {{ . | quote }}
          {{- end }}
        apiVersions:
          {{- range .Values.webhook.rules.apiVersions }}
          - {{ . | quote }}
          {{- end }}
        resources:
          {{- range .Values.webhook.rules.resources }}
          - {{ . | quote }}
          {{- end }}
        scope: {{ .Values.webhook.rules.scope | quote }}
    clientConfig:
      service:
        namespace: {{ include "ssm-annotation-resolver.namespace" . }}
        name: {{ include "ssm-annotation-resolver.fullname" . }}
        path: {{ .Values.webhook.path }}
        port: {{ .Values.webhook.servicePort }}
{{- end }}
