{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ssm-annotation-resolver.namespace" . }}
  labels:
    {{- include "ssm-annotation-resolver.labels" . | nindent 4 }}
{{- end }}
