apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssm-annotation-resolver.serviceAccountName" . }}
  labels:
    {{- include "ssm-annotation-resolver.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.irsa.enabled }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.irsa.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn }}
    {{- end }}
  {{- end }}
  namespace: {{ include "ssm-annotation-resolver.namespace" . }}
  {{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}